version: "3.8"

services:
  nestjs-postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./devops/data/db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
  nestjs-redis:
    image: redis:latest
    env_file:
      - .env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./devops/data/redis:/data"
